/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FIBO_H_RPCGEN
#define _FIBO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input {
	int n;
	int c;
};
typedef struct input input;

struct output {
	int result;
	int series[50];
};
typedef struct output output;

#define FIBOP 2222
#define FIBOV 1

#if defined(__STDC__) || defined(__cplusplus)
#define FIBO 1
extern  struct output * fibo_1(struct input *, CLIENT *);
extern  struct output * fibo_1_svc(struct input *, struct svc_req *);
extern int fibop_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FIBO 1
extern  struct output * fibo_1();
extern  struct output * fibo_1_svc();
extern int fibop_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input (XDR *, input*);
extern  bool_t xdr_output (XDR *, output*);

#else /* K&R C */
extern bool_t xdr_input ();
extern bool_t xdr_output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FIBO_H_RPCGEN */
