/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fibo.h"


void
fibop_1(char *host, int c, int n)
{
	CLIENT *clnt;
	struct output  *result_1;
	struct input  fibo_1_arg;
	
	fibo_1_arg.c = c;
	fibo_1_arg.n = n;

#ifndef	DEBUG
	clnt = clnt_create (host, FIBOP, FIBOV, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = fibo_1(&fibo_1_arg, clnt);
	if (result_1 == (struct output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		displayresult (result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int n, c;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	c = atoi (argv[2]);
	n = atoi (argv[3]);
	fibop_1 (host, c, n);
exit (0);
}
void displayresult (struct output *o)
{
	printf ("Result: %d\n", o->result);
}
